name: wger-dev

services:
  web:
    build:
      pull: true
      context: ${WGER_CODEPATH:?set the absolute path to the wger backend code in the .env file or env variable}
      dockerfile: ./extras/docker/development/Dockerfile
    develop:
      watch:
        - action: sync
          path: ${WGER_CODEPATH}/wger
          target: /home/wger/src
        - action: rebuild
          path: ${WGER_CODEPATH}/requirements.txt
        - action: rebuild
          path: ${WGER_CODEPATH}/requirements_dev.txt
    env_file:
      - ../config/prod.env
      - ../config/dev.env
      - ../config/dev-sqlite.env
    volumes:
      - type: bind
        source: ${WGER_CODEPATH}
        target: /home/wger/src
    ports:
      - "8000:8000"

    command: tail -f /dev/null

  cache:
    image: redis
    expose:
      - 6379
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
