apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    # Uncomment if you enable basic auth on Prometheus (web.yml in compose).
    #basicAuth: true
    #basicAuthUser: "admin"
    #secureJsonData:
    #  basicAuthPassword: "${PROMETHEUS_ADMIN_PASSWORD}"
    jsonData:
      timeInterval: "5s"



