services:
  prometheus:
    image: prom/prometheus:latest
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
    restart: unless-stopped
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./wger.rules:/etc/prometheus/wger.rules
      # Uncomment to enable basic auth on the Prometheus UI.
      #- ./web.yml:/etc/prometheus/web.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      # Uncomment together with the web.yml volume mount above
      #- --web.config.file=/etc/prometheus/web.yml
    expose:
      - 9090
    # Uncomment to  access the Prometheus UI directly
    #ports:
    #  - "9090:9090"
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  grafana:
    image: grafana/grafana:latest
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
    environment:
      - GF_PROVISIONING_DASHBOARDS_ENABLE=1
      - GF_PROVISIONING_DASHBOARDS_PATH=/etc/grafana/provisioning/dashboards
      - GF_PROVISIONING_DATASOURCES_ENABLE=1
      - GF_PROVISIONING_DATASOURCES_PATH=/etc/grafana/provisioning/datasources
    restart: unless-stopped
    volumes:
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"

  loki:
    image: grafana/loki:latest
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
    expose:
      - 3100
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  alloy:
    image: grafana/alloy:latest
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock:ro
    expose:
      - 9080
    command:
      - run
      - /etc/alloy/config.alloy
    restart: unless-stopped
    depends_on:
      - loki

  node_exporter:
    image: prom/node-exporter:latest
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
    restart: unless-stopped
    pid: host
    volumes:
      - /:/host:ro
    command:
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100

volumes:
  prometheus_data:
  loki_data:

networks:
  default:
    name: wger_network
    external: true
