services:
  db:
    image: docker.io/postgres:15-alpine
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
    env_file:
      - ../config/prod.env
    environment:
      - TZ=Europe/Berlin
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    expose:
      - 5432
    # "-c", "log_statement=all", "-c", "log_min_error_statement=DEBUG1"
    command: [ "postgres", "-c", "wal_level=logical" ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$$POSTGRES_USER\""]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
