services:
  cache:
    image: docker.io/redis
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
    expose:
      - 6379
    volumes:
      - ../config/redis.conf:/usr/local/etc/redis/redis.conf
#      - redis-data:/data
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
