services:
  # MongoDB Service used internally
  mongo:
    image: docker.io/mongo:8
    command: --replSet rs0 --bind_ip_all --quiet
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_storage:/data/db
    healthcheck:
      test: |
        test $$(mongosh --quiet --eval "
        try {
          rs.status().ok
        } catch {
          rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'mongo:27017'}]}).ok
        }
        ") -eq 1
      interval: 60s
      start_period: 5s

volumes:
  mongo_storage:
